### ISSUE TITLE
High CPU consumption after last update

### ISSUE THREAD

**Issue by lifehaschanged** [Make-md/makemd#321] opened 2024-05-14 08:24 UTC
Hi, 
the latest update is causing a constant increase in CPU usage, even long after it was activated.
It is not due to other plugins. Even when I disable all settings within the make.md settings, the CPU usage remains consistently high.
Has anyone else the same problem after the last update?

**Comment by jp-cen** [comment] 2024-05-14 13:15
Thanks, I'm prioritizing these performance issues. How many notes do you have?

**Comment by jp-cen** [comment] 2024-05-14 14:43
I have a good idea of where the issue is coming from, but some debug information would be helpful, for example, are you using smart/live search and formula properties?

**Comment by jp-cen** [comment] 2024-05-14 18:29
There's a fix in the next version that should address the CPU issue

**Comment by jp-cen** [comment] 2024-05-14 19:23
Let me know if this is resolved in the newest version

**Closed as completed** 2024-05-16 10:34 UTC
