### ISSUE TITLE
Obsidian hangs when reorganizing folders to the top of the file/spaces view

### ISSUE THREAD

**Issue by scottrlarson** [Make-md/makemd#23] opened 2022-12-23 18:54 UTC
I have been consistently able to get this bug to reoccur. I'm not sure its theme related as I have not tried it in another theme, but I can if need be. The theme I am using is "Typewriter".
Basically what happens is any time I drag a folder to the top of the folder list, the obsidian instance hangs forcing me to reopen it.

Steps to reproduce:
1. Drag a folder to the top position of the list in the files/spaces view.
2. Let go of the mouse button.
3. The  view does not update and the reordering visual indicator sticks or gets stuck.
4. Close and reopen obsidian, the view updates the changes.

The screenshot below shows what the view looks like after releasing the mouse. The view stays this way until I reopen the Obsidian instance.
![Screenshot from 2022-12-23 10-57-34](https://user-images.githubusercontent.com/28913453/209394591-86b43089-af2a-4480-b8ce-e8acc47caf09.png)

Update: updated screenshot to remove private info

**Comment by jp-cen** [comment] 2022-12-23 18:57
Thanks for the report. We’re in the middle of rewriting spaces to be more performant with proper indexing so these issues won’t happen. Will follow up once it’s ready.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Scott Larson ***@***.***>
Sent: Friday, December 23, 2022 1:55:00 PM
To: Make-md/makemd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Make-md/makemd] Obsidian hangs when reorganizing folders to the top of the file/spaces view (Issue #23)


I have been consistently able to get this bug to reoccur. I'm not sure its theme related as I have not tried it in another theme, but I can if need be. The theme I am using is "Typewriter".
Basically what happens is any time I drag a folder to the top of the folder list, the obsidian instance hangs forcing me to reopen it.

Steps to reproduce:

  1.  Drag a folder to the top position of the list in the files/spaces view.
  2.  Let go of the mouse button.
  3.  The view does not update and the reordering visual indicator sticks or gets stuck.
  4.  Close and reopen obsidian, the view updates the changes.

The screenshot below shows what the view looks like after releasing the mouse. The view stays this way until I reopen the Obsidian instance.
[Screenshot from 2022-12-23 10-41-51]<https://user-images.githubusercontent.com/28913453/209393453-57d8621c-5b07-44a9-8321-2f4e6bf8811d.png>

**Comment by jp-cen** [comment] 2022-12-23 19:54
I forgot to mention that all the Spaces settings will be preserved in the migration, so you don’t have to worry about recreating Spaces from scratch. The migration has already been written and tested.

**Comment by jp-cen** [comment] 2023-01-11 01:59
Fixed in 0.6

**Closed by jp-cen** 2023-01-11 01:59 UTC
