### ISSUE TITLE
Make.md changes order of subfolders and files

### ISSUE THREAD

**Issue by DutchPete** [Make-md/makemd#8] opened 2022-11-21 09:57 UTC
Version 0.5.0
OS: Mac

With Make.md disabled, subfolders occur right below the parent folder, and the files in the parent folder occur below the subfolders.

![image](https://user-images.githubusercontent.com/10794265/203020712-5ada97fc-a1fe-44bf-84e1-5bb148cae478.png)

With Make.md enabled, the subfolders occur below the files.

![image](https://user-images.githubusercontent.com/10794265/203020900-caaa9342-f0a0-42dd-ab32-2c2cae105c5a.png)

I checked: this was also the case in 0.4.9.

**Comment by jp-cen** [comment] 2022-11-23 18:03
This is by design as all the folders are sorted by custom, by last created in that order instead of the alphabetical order. Alphabetical sorting will be added to override the custom sort per space. Grouping folders on top can be added as an option

**Comment by DutchPete** [comment] 2022-11-23 18:10
Alphabetical sorting is already **mostly** the case, I don't know why the US and WLD files sneaked to the top when the rest of the files are sorted alphabetically.

> Grouping folders on top can be added as an option

Yes please.

**Comment by Akiriki** [comment] 2022-12-31 08:18
> Grouping folders on top can be added as an option

Yes please! :)

**Comment by jp-cen** [comment] 2022-12-31 13:39
This has been added in the latest preview version and will be fixed in the next release

**Comment by Akiriki** [comment] 2022-12-31 21:04
Awesome, thank you very much!

**Comment by jp-cen** [comment] 2023-01-11 01:56
Resolved since 0.5

**Closed by jp-cen** 2023-01-11 01:56 UTC
